# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_remove_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_id', models.IntegerField()),
                ('buy_year', models.IntegerField()),
                ('buy_month', models.IntegerField()),
                ('buy_day', models.IntegerField()),
                ('goods_id', models.CharField(max_length=10)),
                ('good_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.CharField(max_length=10)),
                ('goods_type', models.CharField(max_length=10)),
                ('goods_name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('buying_price', models.FloatField()),
                ('price', models.FloatField()),
                ('lowest_quantity', models.IntegerField()),
            ],
        ),
    ]
