# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_buy_goodstype_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.IntegerField()),
                ('time', models.CharField(max_length=20)),
                ('goods_id', models.CharField(max_length=10)),
                ('goods_quantity', models.IntegerField()),
                ('username', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='good_quantity',
            new_name='goods_quantity',
        ),
    ]
