# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_auto_20180326_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_id',
            field=models.CharField(max_length=20),
        ),
    ]
