# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0005_auto_20180326_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('goods_id', models.CharField(max_length=10)),
                ('goods_quantity', models.IntegerField()),
                ('username', models.CharField(max_length=10)),
            ],
        ),
    ]
