# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0006_returngoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_id', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('goods_id', models.CharField(max_length=10)),
                ('goods_quantity', models.IntegerField()),
                ('username', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
