# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-25 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0007_auto_20180329_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='lowest_quantity',
        ),
    ]
